import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { getCurrentSession, logout } from '@/api/authentication'
import { IfLoggedIn, IfNotLoggedIn } from '@/component/authentication'

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  fallback: ["inter", 'arial'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const user = await getCurrentSession()
  return (
    <html lang="en">
      <body className={ inter.className }>
        <header>
          <section>
            <h1>🔒 Next.js Simple Auth</h1>
            <a href="/">Home</a>
          </section>
          <form>
            <IfNotLoggedIn>
              <a href="/login" data-primary>Log in</a>
              <a href="/register">Register</a>
            </IfNotLoggedIn>
            <IfLoggedIn>
              <span className="mr-2">
                { user?.username }
              </span>
              <a href="/settings">Settings</a>
            </IfLoggedIn>
          </form>
        </header>
        <main>
          { children }
        </main>
      </body>
    </html >
  )
}
