import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  fallback: ["inter", 'arial'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={ inter.className }>
        <main>
          <header>
            <section>
              <h1>Next Auth Simple Login</h1>
            </section>
            <nav>
              <a href="/" data-inline>Home</a>  
            </nav>
            <br />
          </header>
          { children }
        </main>
      </body> 
    </html>
  )
}
