import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { getCurrentSession, logout } from '@/api/authentication'
import { IfLoggedIn, IfNotLoggedIn } from '@/component/authentication'

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  fallback: ["inter", 'arial'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const user = await getCurrentSession()
  return (
    <html lang="en">
      <body className={ inter.className }>
        <Header>
          <section>
            <p>🔒 <span>Next.js Simple Auth</span></p>
            <a href="/">Home</a>
          </section>
          <section>
            <IfNotLoggedIn>
              <a href="/login" data-primary>Log in</a>
              <a href="/register">Register</a>
            </IfNotLoggedIn>
            <IfLoggedIn>
              <p>{ user?.username }</p>
              <a href="/settings">Settings</a>
            </IfLoggedIn>
          </section>
        </Header>
        <Main>{ children }</Main>
      </body>
    </html >
  )
}

function Header({ children }: any) {
  return <header className="
    flex flex-row items-center justify-between 
    max-w-screen-xl w-full mx-auto  
    px-4
    [&>section]:flex
    [&>section]:items-center
    [&>section]:gap-2
    [&>section>p]:text-xl
    [&>section>p]:font-semibold
    [&>section>p]:text-white
    [&>section_span]:hidden
    [&>section_span]:md:inline
  ">
    { children }
  </header>
}

function Main({ children }: any) {
  return <main className="
    max-w-screen-lg w-full mx-auto
    px-10 pb-24
    break-words
    my-auto

    [&_[data-dialog]]:max-w-sm
    [&_[data-dialog]]:m-auto
    [&_[data-dialog]]:my-auto
  ">
    { children }
  </main>
}